version: "3.8"

services:
  sadcoin-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PROJECT_ID: ${NEXT_PUBLIC_PROJECT_ID}
        GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped
    networks:
      - sadcoin-network

networks:
  sadcoin-network:
    driver: bridge
